resolver: lts-12.24
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: c40ab92fd00f3a8c31f98de308b0409fc8c036f0
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: fd06418f586b53ba45dff88d2927b387f9ab5141
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
