resolver: lts-10.5
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 419e1f05f305d4ced4cec13ec66459223fe76c5b
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
