resolver: lts-7.5
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 257003d90ea0f191ebfd15273cc009cd7463e997
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
