resolver: lts-12.17
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: d7d0dc720d7171c6a7661acf4337626e8bd696b9
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: 7424a8fa15391f5c0e0acd14e4c4459cf8c3dcf4
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
