resolver: lts-12.24
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 6b25057d453146561ea5dd5e3f3bcca46c8d9e77
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: fdc1ae948b18d79420ee2cd1dd290efefe66533d
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
