resolver: lts-12.24
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 342484e8a401d0171874ea408927224a9be4bce2
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: fd06418f586b53ba45dff88d2927b387f9ab5141
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
