resolver: lts-12.17
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 2959559d5399a101d12bb114223352e2a4e1459d
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
