resolver: lts-12.17
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 8a2752b19528e01eaafb20b0acc6de3b56417458
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: 377ce0e0b434e791bff1b3b103ed3b80f46288fd
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
