resolver: lts-10.5
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: 560de341a268b51e51d745007adb3270eb9f5d5d
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
