resolver: nightly-2017-11-27
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: e5b27ed2be0ec4d8fbb5107fe0114a5e70ae9f7e
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
