resolver: lts-12.24
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: dda84aed798a107ceccb12729fe4a0e95790455f
  extra-dep: True
- location:
    git: https://github.com/lamdu/syntax-tree
    commit: 6c4a01cfbc05e6c5cdff75a6136e5f9c71a6c315
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
