resolver: lts-12.7
packages:
- '.'
- location:
    git: https://github.com/lamdu/lamdu-calculus
    commit: caebaca0e6b66c079a307608ee6dfea4df660d2b
  extra-dep: True
extra-deps: []
flags: {}
extra-package-dbs: []
